FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# neobis_rest_framework

This is a test api documetation 

## Course [/courses]

### List All Courses [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "title": "ENglish Zone",
                "description": "This is English language course for students and pupils in Bishkek ...",
                "category": "Language Course",
                "logo": "english.zone.img",
                "contacts": [
                    {
                        "type": "PHONE",
                        "value": "0555025045"
                    },
                    {
                        "type": "FACEBOOK",
                        "value": "english.zone"
                    },
                    {
                        "type": "EMAIL",
                        "value": "english.zone@example.com"
                    }
                ],
                "branches": [
                    {
                        "address": "Biskek Belinka str.",
                        "latitude": "1221.1232",
                        "longitude": "5464.4564"
                    },
                    {
                        "address": "Bishkek Gorkiy str.",
                        "latitude": "2212.1223",
                        "longitude": "3453.3453"
                    }
                ]
            }
        ]

### Create a New Course [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /courses/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }