# Generated by Django 2.1.2 on 2018-10-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='branches',
            new_name='course_branches',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='contacts',
            new_name='course_contacts',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='title',
        ),
    ]
